# Generated by Django 5.2.15 on 2026-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('未完成', '未完成'), ('进行中', '进行中'), ('待确认', '待确认'), ('已完成', '已完成'), ('已取消', '已取消')], default='未完成', max_length=20),
        ),
    ]
